name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
           cd Lab1/Lab1_Task_1.2/Lab1_Task_1.2
           make test
           | 
           cd .. 
           ./Lab1_Test
