name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
      cd Lab1/Lab1(Task 1.2)/Lab1(Task 1.2)
      make Lab1_Test
      ./Lab1_Test
