name: Lab1(Task 1.2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd (/../Lab1/Lab1(Task 1.2)/Lab1(Task 1.2))
    - name: make TEST
      run: cd Programming/Lab1/Lab1(Task 1.2)/Lab1(Task 1.2)/ make TEST
    - name: Lab1
      run: ./Lab1
    - name: Lab1_Test
      run: ./Lab1_Test
