name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
    - run: cd Lab1/Lab1(Task 1.2)/Lab1(Task 1.2)
    - name: make
    - run:  make Lab1_Test
    - name: run
    - run: ./Lab1_Test
