name: Lab1(Task 1.2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd make
    - name: make TEST
      run: cd make TEST
    - name: Lab1
      run: ./Lab1
    - name: Lab1_Test
      run: ./Lab1_Test
