name: Tester(Task 2)

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Super-Linter
      uses: github/super-linter@v3.15.3
    - uses: actions/checkout@v2
    - name: make
      run: |
           cd Lab2/Lab2_Task_2.2/Lab2_Task_2.2
           make test
    - run: |
           cd Lab2/Lab2_Task_2.2/
           ./Lab2_Test
