name: Tester(Lab2 Task1)

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.15.3
    - name: make
      run: |
           cd Lab2/Lab2_Task_2.1/Lab2_Task_2.1
           make test
    - run: |
           cd Lab2/Lab2_Task_2.1/
           ./Lab2_Test
