name: Tester(Lab7)

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
           cd Lab7/Lab7_Task_6.2/Lab7_Task_6.2
           make test
           ./Lab7_Test
           make checkCov
