name: Tester(Lab7)

on:
  push:
    branches: [ main ]
codecov:
  token: 9e6fa2e6-b250-46e1-aed0-2cef039414a7
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
           cd Lab7/Lab7_Task_6.2/Lab7_Task_6.2
           make test
           ./Lab7_Test
           make checkCov
